const festival_list = [
  {
    id: 0,
    media: 'https://assets.maccarianagency.com/backgrounds/img56.jpg',
    title: 'The Big Salsa Fest',
    city: 'Munich',
    country: 'Germany',
    specific_location: 'Hilton Hotel Munich',
    styles: ['Salsa'],
    start: new Date(2022, 8, 2),
    organiser: 'Munich Salsa Movement',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    // ticket: 'http://selinazjw.com',
    contact: 'http://selinazjw.com',
  },
  {
    id: 1,
    media: 'https://assets.maccarianagency.com/backgrounds/img63.jpg',
    title: '12th San Francisco Intl Bachata Festival 2022',
    city: 'San Francisco',
    country: 'USA',
    specific_location: 'snh sdfkj, wsdf',
    styles: ['Salsa', 'Bachata'],
    start: new Date(2022, 8, 22),
    organiser: 'Msdfme msdovement',
    discount: '$10 off',
    // website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com',
    contact: 'http://selinazjw.com',
  },
  {
    id: 2,
    media: 'https://assets.maccarianagency.com/backgrounds/img57.jpg',
    title: 'Aventura Dance Cruise 2023',
    city: 'Florida',
    country: 'USA',
    specific_location: 'fme, Flordans, WUdnsidkgl',
    styles: ['Salsa', 'Bachata', 'Kizomba'],
    start: new Date(2023, 1, 1),
    organiser: 'Msdfme msdovement',
    contact: 'http://selinazjw.com',
  },
  {
    id: 3,
    media: 'https://assets.maccarianagency.com/backgrounds/img58.jpg',
    title: '12th ALOCUBANO Salsa Festival 2022 Stockholm',
    city: 'Stockholm',
    country: 'Sweden',
    specific_location: 'Radisson Blu Royal Park Hotel, Stockholm, Solna, Frösundaviks allé 15, 169 70 Solna, Sweden',
    styles: ['Salsa'],
    start: new Date(2022, 9, 10),
    organiser: 'Msdfme msdovement',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
  {
    id: 4,
    media: 'https://assets.maccarianagency.com/backgrounds/img56.jpg',
    title: 'ALFA 2022 : Afro-Latin Festival Asia ',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    specific_location: 'Kuala Lumpur, Malaysia',
    styles: ['Kizomba', 'Cuban-Salsa', 'Merengue'],
    start: new Date(2022, 8, 30),
    organiser: 'Msdfme msdovement',
    discount: '10% off',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com',
    contact: 'http://selinazjw.com',
  },
  {
    id: 5,
    media: 'https://assets.maccarianagency.com/backgrounds/img63.jpg',
    title: '10th AfroLatin Dance Holidays ',
    city: '',
    country: 'Egypt',
    specific_location: 'Le Passage Cairo Hotel & Casino, Airport Road, Sheraton Al Matar, El Nozha, Egypt',
    styles: ['Kizomba', 'Cuban-Salsa', 'Merengue'],
    start: new Date(2022, 8, 30),
    organiser: 'AfroLatin Egypt',
    discount: '$10 off',
    // website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
  {
    id: 6,
    media: 'https://assets.maccarianagency.com/backgrounds/img57.jpg',
    title: '17th El Sol Salsa Festival 2022',
    city: 'Warsaw',
    country: 'Poland',
    specific_location: 'sdlfw, sdmflwker',
    styles: ['Salsa'],
    start: new Date(2022, 10, 10),
    organiser: 'sdlfkwern and',
    discount: '$10 off',
    website: 'http://selinazjw.com',
    // facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com',
    contact: 'http://selinazjw.com',
  },
  {
    id: 7,
    media: 'https://assets.maccarianagency.com/backgrounds/img58.jpg',
    title: 'Sneakers',
    city: 'Warsaw',
    country: 'Poland',
    specific_location: 'sdlfw, sdmflwker',
    styles: ['Salsa'],
    start: new Date(2022, 10, 10),
    organiser: 'sdlfkwern and',
    discount: '$10 off',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
  {
    id: 8,
    media: 'https://assets.maccarianagency.com/backgrounds/img56.jpg',
    title: 'Mamboland Montreal Rising',
    city: 'Montreal',
    country: 'Canada',
    specific_location: 'Espaces des Arts, Saint Catherine Street East, Montreal, QC, Canada',
    styles: ['Mambo'],
    start: new Date(2022, 7, 12),
    organiser: 'sdlfkwern and',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
  {
    id: 9,
    media: 'https://assets.maccarianagency.com/backgrounds/img63.jpg',
    title: 'Aruba Dance Congress',
    city: '',
    country: 'Carribeans',
    specific_location: 'Aruba Dance Studios, Oranjestad, Aruba',
    styles: ['Salsa', 'Merengue'],
    start: new Date(2022, 8, 1),
    organiser: 'sdlfkwern and',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
  {
    id: 10,
    media: 'https://assets.maccarianagency.com/backgrounds/img57.jpg',
    title: '9th Latin Festival Madras',
    city: 'Chennai (Madras)',
    country: 'India',
    specific_location: 'Vivanta Chennai, IT Expressway, Old Mahabalipuram Road, Elcot Sez, Sholinganallur, Chennai, Tamil Nadu, India',
    styles: ['Salsa', 'Bachata'],
    start: new Date(2022, 8, 1),
    organiser: 'sdlfkwern and',
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
  {
    id:11,
    media: 'https://assets.maccarianagency.com/backgrounds/img58.jpg',
    title: 'London Salsa Marathon',
    city: 'London',
    country: 'UK',
    specific_location: 'London, UK',
    styles: ['Salsa'],
    start: new Date(2022, 7, 20),
    website: 'http://selinazjw.com',
    facebook: 'http://selinazjw.com',
    ticket: 'http://selinazjw.com'
  },
];

const setEndDate = (date) => {
  return new Date(date.getTime()+(2*24*60*60*1000));
};

const mock_festivals = festival_list.map(f => {
  const startDate = f.start;
  const endDate = setEndDate(startDate);
  return {...f, end: endDate };
});

export default mock_festivals;